
import { GoogleGenAI } from "@google/genai";
import { DesignRequest, DesignResult } from "../types";

export const generateDesign = async (request: DesignRequest): Promise<DesignResult> => {
  // Use pro model if high quality is requested, otherwise flash
  const modelName = request.highQuality ? 'gemini-3-pro-image-preview' : 'gemini-2.5-flash-image';
  
  // Re-initialize right before use to pick up any updated key if needed (as per guidelines for Pro/Veo)
  // MUST use new GoogleGenAI({ apiKey: process.env.API_KEY })
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const imageParts = request.images.map(img => ({
    inlineData: {
      data: img.base64,
      mimeType: img.mimeType
    }
  }));

  const systemPrompt = `You are a world-class professional ${request.designType}. 
  Your task is to take the provided image(s) and create a high-fidelity design concept based on them.
  If the user provides a sketch, turn it into a realistic professional design.
  If the user provides a photo, use its aesthetic, color palette, or subject to generate a new creative design.
  Instruction: ${request.instruction}`;

  const response = await ai.models.generateContent({
    model: modelName,
    contents: {
      parts: [
        ...imageParts,
        { text: systemPrompt }
      ]
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1",
        // Only set imageSize if model is gemini-3-pro-image-preview
        ...(request.highQuality ? { imageSize: "2K" } : {})
      }
    }
  });

  let generatedImageUrl = '';
  
  // Find the image part in the response as per SDK guidelines (do not assume first part is image)
  if (response.candidates?.[0]?.content?.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        generatedImageUrl = `data:image/png;base64,${part.inlineData.data}`;
        break;
      }
    }
  }

  if (!generatedImageUrl) {
    throw new Error("No image was generated by the model. Try a more descriptive prompt.");
  }

  return {
    id: Math.random().toString(36).substr(2, 9),
    imageUrl: generatedImageUrl,
    prompt: request.instruction,
    timestamp: Date.now(),
    type: request.designType
  };
};

export const hasApiKeySelected = async (): Promise<boolean> => {
  if (typeof window !== 'undefined' && (window as any).aistudio?.hasSelectedApiKey) {
    return await (window as any).aistudio.hasSelectedApiKey();
  }
  return true; // Default to true if not in an environment that requires it
};

export const openApiKeySelector = async () => {
  if (typeof window !== 'undefined' && (window as any).aistudio?.openSelectKey) {
    await (window as any).aistudio.openSelectKey();
  }
};
